[postgresql]
host = "172.17.0.249"
database = "ifpracesso"
user = "postgres"
password = "M4nut3nc40"

[catraca]
ip = ['172.17.150.1', '172.17.150.2', '172.17.150.3', '172.17.150.4']
tcpport = 3000
buffersize = 1024

#[label]
#height=216
#width=
#columns=
#rows=
#labelwidth=
#labelheight=
#cornerradius=
#leftmargin=
#rightmargin=
#topmargin=
#bottommargin=
#columngap=
